import { join } from "pathe";
import type { NuxtTemplate } from "@nuxt/schema";
import type { SmileBuildConfig } from "@smile/types/build-config";
import { useLogger } from "../utils/module";

export const appTemplates = {
  "app.vue": "app.vue",
};

export function appVueTemplate(config: SmileBuildConfig): NuxtTemplate {
  const { nuxt } = config;
  const logger = useLogger("templates", "app");

  return {
    filename: join(nuxt.options.srcDir, appTemplates["app.vue"]),
    write: true,
    getContents: () => {
      const template = [
        `<script setup lang="ts">`,
        `  // This file was auto-generated by @smile/nuxt`,
        `  // While you can customize this file, you should be sure the following`,
        `  //   remain present:`,
        `  //   - <UApp />`,
        `  //   - <SmileLayout />`,
        `  //   - <NuxtLayout />`,
        `  //   - <NuxtPage />`,
        `  // This will ensure that both \`Smile\` and \`Nuxt\` work as-intended.`,
        `  import { UApp, SmileLayout, NuxtLayout, NuxtPage, NuxtRouteAnnouncer } from "#components"`,
        `</script>`,
        ``,
        `<template>`,
        `  <UApp>`,
        `    <SmileLayout>`,
        `      <NuxtLayout>`,
        `        <NuxtRouteAnnouncer />`,
        `        <NuxtPage />`,
        `      </NuxtLayout>`,
        `    </SmileLayout>`,
        `  </UApp>`,
        `</template>`,
      ];

      return template.join("\n");
    },
  } satisfies NuxtTemplate;
}
